<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCchpbsx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCchpbsx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCchpbsx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCchpbsx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCchpbsx\appDevDebugProjectContainer([
    'container.build_hash' => 'Cchpbsx',
    'container.build_id' => 'b0d09f93',
    'container.build_time' => 1562189971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCchpbsx');
