<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSfd3xw0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSfd3xw0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSfd3xw0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSfd3xw0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSfd3xw0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Sfd3xw0',
    'container.build_id' => '839ab0fd',
    'container.build_time' => 1562162693,
));
