<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEdaxe7u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEdaxe7u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEdaxe7u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEdaxe7u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEdaxe7u\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Edaxe7u',
    'container.build_id' => 'a56e7712',
    'container.build_time' => 1562107710,
));
