<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6g8mezf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6g8mezf/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6g8mezf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6g8mezf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6g8mezf\appProdProjectContainer(array(
    'container.build_hash' => '6g8mezf',
    'container.build_id' => '533fcdba',
    'container.build_time' => 1562006352,
));
