<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'swiftmailer.plugin.redirecting' shared service.

return $this->services['swiftmailer.plugin.redirecting'] = new \Swift_Plugins_RedirectingPlugin($this->parameters['swiftmailer.mailer.default.delivery_addresses'], array());
