<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'white_october.swiftmailer_db.spool' shared service.

return $this->services['white_october.swiftmailer_db.spool'] = new \WhiteOctober\SwiftMailerDBBundle\Spool\DatabaseSpool(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'AppBundle\\Entity\\Email', 'dev', true);
